name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: sbt/setup-sbt@v1
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Run tests
      run: |
        git clone https://github.com/gitbucket/gitbucket.git
        cd gitbucket
        sbt publishLocal
        cd ../
        sbt test
    - name: Assembly
      run: |
        npm install
        npm run-script release
    - name: Upload artifacts
      uses: actions/upload-artifact@v6
      with:
        name: gitbucket-explorer-plugin-${{ github.sha }}
        path: ./target/scala-2.13/*.jar
